# Your application name.
name: '{{APP_NAME|Node IoC app}}'

# The current environment the application is running on
env: '{{APP_ENV|production}}'

# The application locale to be used
locale: '{{APP_LOCALE|en}}'

# The application fallback locale to be used
# if the given locale is either invalid or not supported
fallback_locale: 'en'

providers:
  - '@/lib/providers/AppServiceProvider'
  - '@/lib/providers/ConsoleServiceProvider'
  - '@/lib/providers/RouteServiceProvider'
